### ISSUE TITLE
support for windows

### ISSUE THREAD

**Issue by ipstone** [tldr-pages/tldr-node-client#10]
- it would be nice if it runs on windows

**Comment by sbrl** [comment]
This would be awesome.

**Comment by preco21** [comment]
+1

**Comment by mallowigi** [comment]
It runs on Windows, you just have to modify the "lib/platform.js" and add "win32" to the list of folders (that means you have to fork the repository and install it locally though)

I don't understand why it wasn't supported in the first place since node is usually cross platform.

**Comment by waldyrious** [comment]
@mallowigi if you'd like to submit a PR, it would be very much appreciated. /cc @igorshubovych
