### ISSUE TITLE
Some pages under common inaccessible

### ISSUE THREAD

**Issue by rubenvereecken** [tldr-pages/tldr-node-client#11]
I've got the latest version of this client (freshly installed) and `--update` regularly. Today I noticed I couldn't access the page for `wget`, under `common`. 

I probed around a bit and discovered a very strange trend, which I hope is coincidental. All commands that come behind `touch` in the alphabet can't be found. The ones before like `tmux` are displayed as normal. I tried a lot of other pages that come after `touch` and I can't open any of them. 

I didn't know where the cache is stored but it may have something to do with that?

**Comment by rprieto** [comment]
Wow thanks for finding that @rubenvereecken. I'll investigate see if I get the same issue - really no clue what it could be for now. By default the cache goes into `~/.tldr`.

**Comment by rprieto** [comment]
Update: I don't have that issue locally. What does your cache folder look like? 
Have you tried `--clear-cache` (although that could hide the problem, so maybe not a good idea for now).

**Comment by rubenvereecken** [comment]
This issue is part of #12.
