### ISSUE TITLE
Cannot apply color configuration

### ISSUE THREAD

**Issue by phuongtailtranminh** [tldr-pages/tldr-node-client#112]
## Expected behaviour
The color should be changed

## Actual behaviour
The color didn't change at all

## Log, debug output
I added .tldrrc file to my $HOME folder with this content:

{
  "colors": {
    "text": "green",
    "command-background": "black",
    "command-foreground": "red",
    "command-token": "white"
  }
}

But TLDR doesn't take the effect at all. How can I change the color?

## Environment
OSX Sierra
0.12.5

**Comment by agnivade** [comment]
Please have a look at the solution given on #56. 

TLDR- You have to set a theme and then modify the properties of the theme. The theme support is incomplete and #56 tracks that feature. Hence, marking this as duplicate. Please let me know if that solution does not solve your issue.
