### ISSUE TITLE
Possible to do the initial --update on first run instead of on postinstall?

### ISSUE THREAD

**Issue by dikarel** [tldr-pages/tldr-node-client#119]
Instead of running the initial `--update` on postinstall, I wonder if it's possible to do so on first run instead? It would cause the least amount of surprise that way.

Right now, installing this package with sudo requires running a different command than `npm install -g tldr`. This is not mentioned in [tldr's main site](http://tldr-pages.github.io), and breaks certain flows (e.g. mass-install npm packages via devops tools).

**Comment by agnivade** [comment]
Note that npm's [documentation](https://docs.npmjs.com/getting-started/installing-npm-packages-globally) recommends not to use `sudo` while doing `install -g`. But anyways, yes we can easily fix the documentation on the main site. It is mentioned in the node client repo though.

Having said that, I am not saying that we should go on with the post-install approach. Its quirky and unexpected. Coming to a proper fix, doing it in the first run would need state to be maintained in the client. We can write to a file saying that `tldr` has run for the first time, but that seems a bit crude. And then you have to check that file every time you run the command. I am open to other suggestions. :)

**Comment by waldyrious** [comment]
We could simply check if the `pages/common/tldr.md` file exists, as a proxy for a dedicated init file :) would that work?

**Comment by agnivade** [comment]
Hmm .. I am thinking something like this - if we do not run the `--update` command post install, cache will be empty. So, upon running any command, if that page is not found, it can simply run the `--update` and populate the cache. This has the advantage of not running any side logic of checking whether `tldr` is being run for the first time or not, and also automatically solves #9 too.

Only downside is it hurts the first use. But I guess its a decent tradeoff.

**Comment by waldyrious** [comment]
Well, the first use can be just delayed (wait for the update to conclude), not outright skipped, in case you were thinking of such a workflow. This is what Homebrew does, IIRC.

**Comment by agnivade** [comment]
>  the first use can be just delayed (wait for the update to conclude), not outright skipped,

Of course I meant delayed :) But yea .. it still hurts.
