### ISSUE TITLE
`tldr sort` tries to find the `tldr-sort` command

### ISSUE THREAD

**Issue by rubenvereecken** [tldr-pages/tldr-node-client#15]
This was extremely weird. I didn't bother to even try and find the source of this strange bug but I might later on.

`tldr sort` threw me the following error after correctly displaying the page for sort:
```
module.js:340
    throw err;
          ^
Error: Cannot find module '/usr/local/bin/tldr-sort'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

This is just a bit silly, right? I tried `tldr ls` and it didn't have the problem.

**Comment by rprieto** [comment]
That's very odd indeed :open_mouth: 
I have the same behaviour locally.
