### ISSUE TITLE
don't rely only on color to identify the keywords

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr-node-client#18]
For commands like [head](https://github.com/tldr-pages/tldr/blob/master/pages/linux/head.md) which can have two options one next to the other, it is not clear when one option ends and the other starts. Also, we can't visually distinguish a 3-word option description from three one-word options except from context. How about preserving the `{{}}` or replacing them with another marker like `<>`?

**Comment by rprieto** [comment]
It's a fair concern, but I personally like that the output is very easy to read (no extra symbols).
I imagine we could have several rendering options in `.tldrrc`, e.g.

```json
{
  "repository": "tldr-pages/tldr",
  "rendering": {
    "wrapSymbols": true,
    "ansiColors": true,
    "ansiPalette": {
      "text": "green",
      "command-background": "black",
      "command-foreground": "red",
      "command-token": "white"
    }
  }
}
```

**Comment by waldyrious** [comment]
I don't think it's a good idea to let the default setting allow keywords (options) to be confused for the sake of visual simplicity. How about requiring all multi-word options to include a hyphen (or underscore, or period...) instead? Or adding extra spaces between different options?

**Comment by rprieto** [comment]
Ah yes sorry just got what you mean... I was being a little slow.
Definitely not great if the options have whitespace... let's discuss over at https://github.com/tldr-pages/tldr about requiring underscores or similar, and we can also fix it over here to be safe?

**Comment by waldyrious** [comment]
While on the one hand I agree that it's better to prevent this issue at the source, I'm not convinced that using separator characters is a better choice than visible wrapping symbols (especially since the `<...>` format is a [widespread convention](http://docopt.org/)). If you're adamantly against the latter, then sure, the main tldr repo seems like a better place to discuss this. Otherwise, it makes more sense to implement the conversion from `{{}}` in the clients (unless we can/should replace the markers in the source as well)

**Comment by rprieto** [comment]
Mmm I see what you mean. The `tldr` pages already have `{{some words}}` so it's not ambiguous. Maybe this is a client concern... in which case I don't have anything strongly against rendering `<some words>` if we think it's better.

That being said, initially the aim was to have `tldr` pages like `head -n 10 file.txt`, which doesn't have the same problem as `head -n number of lines path to file`.

**Comment by waldyrious** [comment]
Took me a while to find the thread where we discussed what tokens should be. I managed to find https://github.com/tldr-pages/tldr/pull/74 but some comments there seem to indicate there was another discussion, which I couldn't find. Regardless, from the 3 options you listed in that discussion, apparently the 3rd one ("something in between" actual examples and descriptive names) was adopted, since [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) currently reads "Use short but descriptive values for the tokens, ex. `{{source_file}}` or `{{wallet.txt}}`." Interestingly, it seems to implicitly suggest underscores for separating words, so we could go with that as well, and perhaps mention that explicitly in CONTRIBUTING.md.

Should we ping [frequent contributors](https://github.com/tldr-pages/tldr/graphs/contributors) to this discussion so they could share their opinion on what format we should use (either in tldr or in the clients)? I'd point out that since we don't control every client, it might be hard to ensure consistent rendering, so that's an argument for fixing this at the source; nevertheless, adopting the "docopt" pattern makes sense as well IMO, and would allow the raw markdown files to be more readable.

**Comment by waldyrious** [comment]
@rprieto ping :)

**Comment by waldyrious** [comment]
Underlining may be a good second signal to avoid depending on color alone. Example screenshot in https://github.com/tldr-pages/tldr-python-client/pull/25.

**Comment by zdroid** [comment]
Has this been resolved? Default theme for node client uses underlines instead of colors.

**Comment by agnivade** [comment]
Yes, underlining is a theme option and can be applied with any theme.
