### ISSUE TITLE
Add zdroid as collaborator

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr-node-client#197]
In the course of https://github.com/tldr-pages/tldr/issues/1878, based on [zdroid's existing contributions](https://github.com/tldr-pages/tldr-node-client/commits?author=zdroid) to this repo, I've invited him as a collaborator. All the other [frequent contributors](https://github.com/tldr-pages/tldr-node-client/graphs/contributors) already have access as either repo collaborators or organization owners.

For future reference, note that further additions should follow the process which is now being defined in https://github.com/tldr-pages/tldr/pull/1897.

Welcome, @zdroid, and thanks for the work you've done so far!

**Comment by waldyrious** [comment]
(Leaving this open until @zdroid accepts or declines the invitation.)

**Comment by zdroid** [comment]
Thanks @waldyrious, I was a bit inactive lately. I'll try my best to help on the node client.

**Comment by waldyrious** [comment]
@zdroid no pressure! This is not an attribution of a responsibility, but rather a removal of barriers that at this point are more inconvenient than helpful, since your past contributions already demonstrated that you have both the skill and the will to improve this code.

Of course, you're welcome to help out with maintenance of the repo, since you now can, but that's by no means an obligation -- this is a collaborative, volunteer project, after all ;)

**Comment by waldyrious** [comment]
For your first action as a collaborator, how about closing this issue yourself? :)

**Comment by zdroid** [comment]
You are right, I haven't noticed the comment in the load of emails. :closed_lock_with_key:

**Comment by waldyrious** [comment]
No problem 👍
