### ISSUE TITLE
Move autocompletion.zsh for easy usage with zplug

### ISSUE THREAD

**Issue by BonaBeavis** [tldr-pages/tldr-node-client#202]
Moving `bin/autocompletion.zsh` to `bin/completion/_tldr` enables oneliner to integrate tldr with zplug (zsh):

```
zplug "tldr-pages/tldr-node-client", use:bin/completion/
```

**Comment by agnivade** [comment]
How do you do it currently (Not a zsh user) ? Do you have to rename the file ?

**Comment by BonaBeavis** [comment]
Yes

**Comment by agnivade** [comment]
ping @ronjouch. Thoughts/comments ?

**Comment by agnivade** [comment]
@BonaBeavis - There are two autocompletion files- one for bash and zsh. If we rename the zsh one to be without the extension, then it looks odd to have a file ending with `.bash` and the other `_tldr`. Thoughts ?

**Comment by BonaBeavis** [comment]
Just add an folder for both shells ala https://github.com/docker/cli/tree/master/contrib/completion
