### ISSUE TITLE
Improve multi-user usage

### ISSUE THREAD

**Issue by bryanspears** [tldr-pages/tldr-node-client#208]
## Expected behaviour
Should allow more than one user to use tldr

## Actual behaviour
When attempting to update the cache, it fails due to using a hardcoded path if another user has run tldr before you. This also occurs on first run because it hasn't setup local cache or config.

## Log, debug output
```
Updating{ Error: EACCES: permission denied, rmdir '/tmp/tldr/pages'
  errno: -13,
  code: 'EACCES',
  syscall: 'rmdir',
  path: '/tmp/tldr/pages' }
```
## Environment
- Operating system - Linux
- NodeJS version - 6.9.1

**Comment by agnivade** [comment]
Interesting. Can you mention your tldr version and the steps to reproduce the issue ?

The zip archive is just temporarily downloaded to /tmp/ after which it is copied under the respective user's `$HOME/.tldr` directory. So, I'm not sure why there is an error while accessing /tmp/. 

Is this about multiple users concurrently trying to execute tldr ?

**Comment by bryanspears** [comment]
`/tmp/tldr/pages` is not removed after the temporary path is done being used. It's not about concurrency. The directories are owned by the previous executing user and the following user can't write to the static path.

Using tldr version 3.2.1

Should be simple to add two things:
- Generate a temp path. Don't use a static path.
- Clean up tmp path after the cache build is complete

**Comment by agnivade** [comment]
Got it. Thanks.
