### ISSUE TITLE
Vulnerability: hoek should be updated to 5.0.3

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr-node-client#211]
The package `hoek` is specified in the `package-lock.json` file at version `4.2.0`. When I run `npm-remote-ls hoek` though, it tells me that version 5.0.3 will suffice. I suggest updating it to mitigate the vulnerability that GitHub has identified.

Here's the reverse-dependency tree generated by `npm-remote-ls`: https://hastebin.com/enirizinan

**Comment by vladimyr** [comment]
> I don't know if manually editing package-lock.json is a good idea.

According to my experience that is a bad idea and should be avoided if possible.

> Hrm true. What I ended up doing for another of my projects is deleting package-lock.json, and using node-check-updates

I haven't used `ncu` in a while but as far as I remember it alters `package.json` only. Subsequent `npm install` will respect changes and update `package-lock.json` accordingly so you don't need to delete it manually and wait for it to get _re-_ generated. :wink: 

Keeping packages _green_ is typically a good idea but it is also a risky business by definition. If you do it manually try [`npm-check`](https://npm.im/npm-check). It has nice interactive mode and it will warn you about potentially breaking updates.
Mitigating vulnerabilities is another story and it should be done (semi-)automatically relying on 3rd party service to keep track of affected dependencies and bumping those.

Naturally there are dedicated bots providing both services:
1. keeping stuff _green_: https://greenkeeper.io/ or https://renovatebot.com/
2. keeping stuff _safe_: https://snyk.io/

All 3 are free for OSS so maybe this is a chance to setup something to avoid future security issues. What do you think @agnivade ?
