### ISSUE TITLE
Perform search if command is not found on current OS

### ISSUE THREAD

**Issue by amejiarosario** [tldr-pages/tldr-node-client#247]
## Expected behaviour
When looking for a command that is not found. It should perform a `--search` on it.

## Actual behaviour
For instance, I was looking for `ss` (on OSX)
![image](https://user-images.githubusercontent.com/418605/52135751-7f646c80-2614-11e9-9ecf-3a798c7f8ae4.png)

I thought, "Oh this command is missing on docs"...

But then, I saw there's an entry for it in linux and if I use `--search`:
![image](https://user-images.githubusercontent.com/418605/52135803-a1f68580-2614-11e9-97cf-187b1a03699e.png)

It would be really nice, if it can give this results automatically if not result was found on my current operating system.

## Log, debug output
Put any log or error output here.

## Environment
- Operating system: OSX  MacOS Mojave v10.14.2
- NodeJS version: 8.12.0

**Comment by agnivade** [comment]
`--search` is only meant as a keyword search for pages. I agree that it should report if a page was found for other platforms, but it should not do `--search`.

**Comment by agnivade** [comment]
This is now fixed to automatically search pages for other platforms and display them.
