### ISSUE TITLE
Character "<" (less) is rendered as "≪"

### ISSUE THREAD

**Issue by igorshubovych** [tldr-pages/tldr-node-client#25]
Consider the following page

~~~Markdown
# bc

> Calculator.

- Calculate the result of expression

`bc <<< "(1 + 2) * 2 ^ 2"`
~~~

It is rendered
```
  bc
  Calculator.

  - Calculate the result of expression
    bc ≪≪≪ "(1 + 2) * 2 ^ 2"
```

It is wrong and cannot be safely copy-pasted to run in CLI.

**Comment by rprieto** [comment]
Thanks, this could be related to https://github.com/hughsk/unhtml/pull/2 (although it was about `&lt;` but sounds very similar).

**Comment by igorshubovych** [comment]
Most likely.

We probably should use other library
`Latest commit 359e1c0  on Mar 4, 2013`
