### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by linonetwo** [tldr-pages/tldr-node-client#253]
I'd like to use this in my https://github.com/linonetwo/hyper-visual

But How to call this package in Javascript?

**Comment by agnivade** [comment]
Import the package and use the `lib` folder. Most of the logic is called from there. See https://github.com/tldr-pages/tldr-node-client/blob/master/bin/tldr.

**Comment by vladimyr** [comment]
```js
const tldr = require('tldr/lib/tldr');
// prints page to stdout
tldr.get(['tar']);
// prints raw version
tldr.get(['tar'], { markdown: true });
```

However keep in mind:
1. It writes both to `stderr` (spinners) and `stdout` (actual tldr page)
2. `tldr#get` does not return `Promise` so you don't really now when it ends

**Comment by linonetwo** [comment]
Seems most functionality depends on `cache`, so I tried to import it:

```import cache from 'tldr/lib/cache';```

But it throws an error:

`bundle.js:1 Error: ENOENT: no such file or directory, open '/config.json'`

I'm trying to output this to a GUI, so I need to get the raw output. Am I doing right?

**Comment by agnivade** [comment]
You need a config.json file in your current directory See https://github.com/tldr-pages/tldr-node-client/blob/master/config.json.

It will be difficult to get raw output to a variable. The library directly writes to the console.

**Comment by linonetwo** [comment]
where can I put that config.json?

I'm import it like this: https://github.com/linonetwo/hyper-visual/blob/add-tldr/src/components/TLDR.js#L9

This is a terminal's plugin, so it's bundled by webpack.

I tried to put config.json into `./dist` and `./` and `./src/components`, but it always throws `no such file or directory, open '/config.json'`

**Comment by linonetwo** [comment]
I know how to do it:

https://github.com/linonetwo/zazu-tldr/blob/master/src/index.js
