### ISSUE TITLE
Please catch error when updating cache

### ISSUE THREAD

**Issue by linonetwo** [tldr-pages/tldr-node-client#256]
## Expected behaviour

No "internal error" thrown, instead, a catchable Error thrown.

## Actual behaviour
Tell us what happens instead.

Randomly throwing one of the following errors when Wifi is off:

```

A JavaScript error occurred in the main process
Uncaught Exception:
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:182:27)

A JavaScript error occurred in the main process
Uncaught Exception:
Error: socket hang up
    at createHangUpError (_http_client.js:334:17)
    at Socket.socketOnEnd (_http_client.js:435:23)
    at Socket.emit (events.js:199:15)
    at endReadableNT (_stream_readable.js:1141:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

And I can't simply catch this error.

## Environment
- Operating system - OSX 10.14.4 (18E226)
- NodeJS in electron:

Electron Version: 5.0.1
Node Version: 12.0.0
Chrome Version: 73.0.3683.121

**Comment by agnivade** [comment]
@linonetwo - Can you please check with tldr latest version 3.3.6 if the issue has been fixed? Thanks!

**Comment by linonetwo** [comment]
Wow, glad to see this can get a fix, I was using this for https://github.com/linonetwo/zazu-tldr , but it is not maintained and not used recently...

I will revisit this in 2021 after I finish my other opensource projects, thank you!
