### ISSUE TITLE
When tldr is invoked with --update, it shouldn't tell me to run --update

### ISSUE THREAD

**Issue by jgreco** [tldr-pages/tldr-node-client#272]
## Expected behaviour

```
> tldr --update
[nothing is printed]
```

## Actual behaviour
```
>tldr --update
Local data is older than two weeks, use --update to update it.
```

I know it's not really a huge deal, but it seems silly for tldr to remind me to update when I just decided to do precisely that.

**Comment by schneiderl** [comment]
I would be glad to tackle this but in my opinion another message should be printed in this case. 

"local data was updated"? do you guys have any suggestions?

**Comment by agnivade** [comment]
Can you specify your tldr version please ? I don't see it with 3.2.7.

**Comment by jgreco** [comment]
Ah crap you're right, I actually have the CPP client, v1.3.0
