### ISSUE TITLE
Question: How to get translated pages

### ISSUE THREAD

**Issue by KsRyY** [tldr-pages/tldr-node-client#273]
Just as the title, how could I get the translated pages from this client?

**Comment by agnivade** [comment]
It is not supported yet. Please see #270.

**Comment by KsRyY** [comment]
So it's a Work In Progress?

**Comment by KsRyY** [comment]
Because I am doing the translation work in the main repository so I am curious about this.

**Comment by agnivade** [comment]
Work has been paused for now because we need to change the spec to GNU language tags. And then change the folder names too. Only after that work can resume. So I cannot say when will that happen.

**Comment by KsRyY** [comment]
Thanks.

**Comment by sbrl** [comment]
For reference, the PR you probably want to subscribe to is [this one](https://github.com/tldr-pages/tldr/pull/3168) on the main repository. Once that gets merged, work can resume here.

Note that other clients already have preliminary support for multiple languages. Try exploring client implemented in other languages in the mean time!

**Comment by agnivade** [comment]
Going to close this now. I believe the question has been answered.
