### ISSUE TITLE
Question/request: Configure location of .tldr folder

### ISSUE THREAD

**Issue by zmeeagain** [tldr-pages/tldr-node-client#275]
Can the location of `.tldr` folder be configured/changed?

## Expected behaviour
Be able to configure/change location of `.tldr` folder.

## Actual behaviour
Current location of .tldr folder is %HOME%/.tldr

## Environment
- Windows
- NodeJS version: v11.13.0

**Comment by agnivade** [comment]
It's not configurable, and there hasn't been any request to do so. Like any other app, it stores it in a config directory. Arguably, it is not XDG_CONFIG_HOME compliant. But that's orthogonal. Is there a reason you want it configurable ? All unix apps should store their config in a standard location according to XDG spec.

**Comment by zmeeagain** [comment]
Due to some silly corporate policies I am trying to optimise space/number of files on home drive.
I was thinking something along the lines of `yarn` or `npm`, where you can configure cache, data folders' location.

**Comment by agnivade** [comment]
You can achieve that with a simple symlink.

**Comment by zmeeagain** [comment]
Well, that's what I had in mind initially. Just wanted to check.
tx

**Comment by sbrl** [comment]
I guess we could add support for a `TLDR_DIR` environment variable? But yeah a symbolic link seems to be the most effective solution here. I assume you're using Linux?

If you're a Windows user then a directory junction (NTFS only, IIRC) may be what you're after.

**Comment by zmeeagain** [comment]
Yes, a junction seems to work for space.  However, I realized that this will not prevent the delay when it is ceremoniously backed-up/restored (no control on that) - I know, this is not the most common use case, but there you go. Having an optional environment var to override that would be perfect.

**Comment by sbrl** [comment]
Backed up / restored? Not quite sure you what you mean by that.

**Comment by zmeeagain** [comment]
I am at a client where home gets backed-up and junctions are followed and their actual content is copied too.

**Comment by sbrl** [comment]
Ah, I see. Could you not add an exclusion rule to the backup?

**Comment by zmeeagain** [comment]
Nope, there are some predefined exclusions but cannot add to that list yet. I have made a request but wouldn't hold my breath.

**Comment by vladimyr** [comment]
If you have persistent and solid connection you can try this: https://github.com/vladimyr/tldr-lite
It uses github directly without caching pages locally. :bulb:

**Comment by zmeeagain** [comment]
Yes, I suppose that might be an option, I will give it a go.
