### ISSUE TITLE
Failing tests: AssertionError: expected Array [] to equal Array [ ... ] (at length, A has 0 and B has 9)

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr-node-client#288]
What's happening to Windows builds and why are they constantly failing? The error shown on Appveyor seems totally unrelated to OS.

ping @igorshubovych (the Appveyor says project is listed under his nick there)

**Comment by sbrl** [comment]
What does the transcript say, if you're able to access it?

**Comment by zdroid** [comment]
This is it: https://ci.appveyor.com/project/igorshubovych/tldr-node-client-bnut4

**Comment by sbrl** [comment]
Hrm. It looks like it all start to go wrong here: https://ci.appveyor.com/project/igorshubovych/tldr-node-client-bnut4/build/job/xlnt8x4ib34asam0#L165

**Comment by vladimyr** [comment]
@sbrl There is also failed assertion above that one.

**Comment by sbrl** [comment]
Oops, I must have missed it @vladimyr

**Comment by vladimyr** [comment]
Seems like nobody here is a windows guy 😀

**Comment by sbrl** [comment]
IIRC tldr-pages did start as a macOS project before expanding to Linux and Sunos (/Solaris?), and Windows was only recently added lol (the only one I was around for), so I guess it makes sense :P
