### ISSUE TITLE
Stable snap package is broken

### ISSUE THREAD

**Issue by jerkstorecaller** [tldr-pages/tldr-node-client#289]
Running Ubuntu 18.04, but it's snap so it shouldn't matter.

The stable snap package is 3.1.0 from 2017, and it doesn't work. When using tldr the first time, it says "page not found, updating cache", and then just eats CPU forever. Uninstalling the snap then installing the --edge snap (3.3.2), tldr updates the cache properly and works.

Considering how old the snap is, it's safe to presume it's abandoned. I think if users are meant to use the edge channel only, then you should unpublish the stable package from the snap store, to avoid having people waste their time troubleshooting.

**Comment by vladimyr** [comment]
> Considering how old the snap is, it's safe to presume it's abandoned. I think if users are meant to use the edge channel only, then you should unpublish the stable package from the snap store, to avoid having people waste their time troubleshooting.

I would actually go one step further and say it is completely abandoned due to: https://github.com/tldr-pages/tldr-node-client/issues/276#issuecomment-549809850 (read next few comments)

**Comment by jerkstorecaller** [comment]
@agnivade can you please unpublish the stable tldr from the Snap store? This is just extremely annoying. Keeping a broken tool there for so long is a waste of everyone's time. This isn't something I can do for you in a pull request, unless you give me your username and password.

If you've been thinking "I plan to fix it soon, just need some more time", don't. Delete the broken package right now, then take however much time you need to fix it. Or never, that's OK too! Just don't leave people downloading your broken package by default.

**Comment by vladimyr** [comment]
> Keeping a broken tool there for so long is a waste of everyone's time. This isn't something I can do for you in a pull request, unless you give me your username and password.

While you can't remove the broken version from the snap store (or upload working one) you can send PR that (temporarily) removes snap installation instructions so fewer people would waste their time.

> Delete the broken package right now, then take however much time you need to fix it. Or never, that's OK too! Nothing wrong with that. Just don't leave people downloading a broken package by default.

As much you are right and I sympathize with your cause you can't really demand stuff.

> If you're busy, maybe someone you trust can use your credentials to delete your Snapcraft packages for you?

I have never administered a snap package so maybe you can help me with this one. Can you have a team that shares publish rights or can rights to _allocated_ name get transferred to another account?

**Comment by agnivade** [comment]
My apologies. Apparently, I cannot remove a snap from the store, I can only make it private. I have done that now, and also closed the edge and stable channels.

Sorry for the troubles. I wasn't ready to take on the responsibility to maintain another release method. And it's clear that snap packages have their own way of isolating filesystem access which causes failures in unexpected ways. It is recommended to just use the npm package.

**Comment by vladimyr** [comment]
@agnivade Do we have this https://snapcraft.io/build configured? 🤔

**Comment by agnivade** [comment]
@vladimyr -  I just removed it. I'll remove the .snapcraft.yml file next. Thanks for the heads up.

**Comment by kbdharun** [comment]
Hello guys,

An update on this, I have recreated the Snap package based on the Python client instead (with the help of a friend experienced with Snaps), the configuration file can be [found here](https://github.com/tldr-pages/tldr-python-client/blob/main/snap/snapcraft.yaml). In the future, we will be actively maintaining the packages and releases for the Snap package.

**Comment by sbrl** [comment]
Hey there, @kbdharun. It would be very helpful if I could have the account details, but I can't figure out which account you are on Gitter. Can you message me please? We can work out a secure way of exchanging credentials - e.g. using GPG.

**Comment by kbdharun** [comment]
> Hey there, @kbdharun. It would be very helpful if I could have the account details, but I can't figure out which account you are on Gitter. Can you message me please? We can work out a secure way of exchanging credentials - e.g. using GPG.

Sure, I will send you a message. While I do have a Gitter account (created for Tldr I am no longer actively using it since we moved to Matrix). My main account is @kbdk@matrix.org
