### ISSUE TITLE
Feature request: command palette with fzf

### ISSUE THREAD

**Issue by kschurter** [tldr-pages/tldr-node-client#312]
![Screenshot from 2020-10-02 05-33-19](https://user-images.githubusercontent.com/47160422/94909351-0c5a6b80-0471-11eb-9494-b395dc5f0463.png)
## Environment
- Linux (Pop 20.04)
- Bash

I would like to open discussion about integration with fzf along these lines. I found this command palette useful because I am a noob and have to google for the right terms to search in the tldr/man pages. Suggestions for a more elegant solution or additional features are welcome.

At the command line:
```
$ cd ~/.local/share/tldr/pages/common
$ grep "^-\|^\`" ./{common,linux}/* | awk 'BEGIN {FS=":[`-]"; OFS="\0"}; /md:-/ {gsub(".*/","",$1); desc=$2; f=$1; next} {gsub("`$","",$2); printf "%s%s\033[35m%s%s %s\033[0m\n", $2, OFS, desc,
OFS, f;}' > ~/.tldrpalette
```
In .bashrc:
```
__fzf_command_palette__() {
    local output
    output=$(fzf --ansi --no-hscroll --query "$READLINE_LINE" --delimiter "\0" --preview 'cat $(fd ^{3}$ 
    ~/.local/share/tldr/pages/{common,linux})' --preview-window=hidden:wrap --bind='ctrl-/:toggle-preview' < ~/.tldrpalette | cut -f 1 -d "" ) || return
    READLINE_LINE=${output#*$'\t'}
    if [ -z "$READLINE_POINT" ]; then
        echo "$READLINE_LINE"
    else
        READLINE_POINT=0x7fffffff
    fi
}
bind -m emacs-standard -x '"\ep": __fzf_command_palette__'
bind -m vi-command -x '"\ep": __fzf_command_palette__'
bind -m vi-insert -x '"\ep": __fzf_command_palette__'
```

**Comment by agnivade** [comment]
Sorry, I'm only vaguely aware of `fzf` as a tool which gives you list of outputs that you can select from.

Are you suggesting that the fzf command give the list of pages that you can filter and then display?

I am not sure what role does the node client play in this. You could just do a git clone of the pages repo and run fzf on top of that.

Sorry if I have misunderstood something. It's not very clear to me what you mean by "integration with fzf".

**Comment by kschurter** [comment]
I added a screenshot to my original post. Pressing Alt+p in my terminal brings up a screen as pictured. I can then do a fuzzy search for the line I want. Pressing enter copies the command (all the text in white) to readline so that I can edit and execute.

**Comment by kschurter** [comment]
Ok so there is another project that has very similar functionality already: https://github.com/pindexis/marker. I still like having the ability to toggle the preview of the *.md file within fzf, so I am sticking with my shell function. But, inspired by this other project, I added some more vi-style keyboard macros and modified READLINE_POINT in my shell function. I'll close this issue now. 

Thanks for bearing with me. And thank you for your work on this project. It is a great resource.

In case others find it useful, my .bashrc now includes

```
__fzf_command_palette__() {
    local output
    output=$(fzf --ansi --no-hscroll --query "$READLINE_LINE" --delimiter "\0" --preview 'mdcat
 $(fd ^{3}$ ~/.local/share/tldr/pages/{common,linux})' --preview-window=hidden:wrap < ~/.tldrpa
lette | cut -f 1 -d "") || return
    READLINE_LINE=${output#*$'\t'}
    # position the cursor before the first occurrence of '{{'
    # can try to use <tab><tab> to show completion options for first {{placeholder}}
    local pattern="{{*"
    local substr=${READLINE_LINE%%$pattern}
    local index=${#substr}
    READLINE_POINT=$index
}

bind -m emacs-standard -x '"\ep": __fzf_command_palette__'
bind -m vi-command -x '"\ep": __fzf_command_palette__'
bind -m vi-insert -x '"\ep": __fzf_command_palette__'
bind -m vi-insert '"\ej": "\ef{2cf}"'   # Alt+j deletes next {{placeholder}}
bind -m vi-insert '"\ek": "\e2F{2cf}"'   # Alt+k deletes previous {{placeholder}}
```
