### ISSUE TITLE
Release version 3.3.4 to npm?

### ISSUE THREAD

**Issue by omBratteng** [tldr-pages/tldr-node-client#317]
The latest version of tldr released on [npmjs.com](https://www.npmjs.com/package/tldr) is `3.3.2`, and latest release on github is `3.3.4`

**Comment by agnivade** [comment]
That's a bit weird. I thought I had pushed them to npm. I will check.

**Comment by agnivade** [comment]
Done. Also released a new one with 3.3.5 pointing to latest master.
