### ISSUE TITLE
tldr changes command line font color and doesn't change it back.

### ISSUE THREAD

**Issue by fireattack** [tldr-pages/tldr-node-client#323]
## Expected behaviour
After running `tldr`, it should change the font color back to CMD default (whatever the user sets to. The default is 192,192,192).

## Actual behaviour
After running some commands, it changes the font color "permanently" (in current window) to pure white.
## Log, debug output
Put any log or error output here.

![bug](https://user-images.githubusercontent.com/4130991/102000303-d07f2600-3cab-11eb-9cc7-8906451cd385.png)

The left is what the default looks like. The right one is what it looks like after I run `tldr exiftool`.

## Environment
- Operating system - Windows  10
- NodeJS version 12.9

**Comment by agnivade** [comment]
@owenvoke - IIRC, you have a Windows system? I'm not sure if this is a `chalk` issue or something with the codebase. Would you be open to take a look?

**Comment by owenvoke** [comment]
Sure, I'll have a look shortly. 👍🏻

**Comment by owenvoke** [comment]
Hmm, I've tested this locally on my Windows machine and wasn't able to replicate the issue. 🤔

**Comment by fireattack** [comment]
Hmm. I can reproduce it with PowerShell too

![image](https://user-images.githubusercontent.com/4130991/102315852-7942b500-3f3a-11eb-947d-bca323a22224.png)

I'm using the version installed from `npm` (3.3.6.)

**Comment by agnivade** [comment]
@fireattack - Just to confirm, you are using the latest tldr version 3.3.6 right?

**Comment by fireattack** [comment]
I install it from `npm`, it shows 3.3.6 when using `--version`, yes.

**Comment by agnivade** [comment]
Alright, it's really difficult for us to look into this if we are unable to reproduce.

I don't use Windows so unfortunately I am useless here. If you are willing to look into this by yourself, a PR will be most welcome :)

**Comment by owenvoke** [comment]
For reference, here are my terminal screenshots (CMD, PowerShell, Windows Terminal). All using the latest tldr node client. 👍🏻

![Preview screenshots](https://user-images.githubusercontent.com/1899334/102328959-abc2d100-3f7f-11eb-9c88-33b25e69448c.png)

**Comment by fireattack** [comment]
Maybe it's related to node version? Would you mind to tell what version of node do you use?

**Comment by owenvoke** [comment]
@fireattack, I'm using Node v15.4.0

**Comment by fireattack** [comment]
Hi, I just happened to reinstall my OS (for other reasons) entirely and now this bug is gone, even with 12.19.

I consider it's non-issue and close this, Thanks for your help!
