### ISSUE TITLE
npm installed but not work with "SyntaxError: Unexpected token"

### ISSUE THREAD

**Issue by d0ye** [tldr-pages/tldr-node-client#331]
## Expected behavior
install with `  npm install -g tldr ` but can't work, And I'm not familiar with js syntax

## Actual behaviour
[root@centos ]# tldr
/usr/lib/node_modules/tldr/node_modules/fs-extra/lib/index.js:5
  ...require('./fs'),
  ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/tldr/lib/tldr.js:4:12)

## Environment
- Operating system - OSX/Linux/Windows (add version if needed)
Centos 7.7
- NodeJS version
v6.17.1

**Comment by vladimyr** [comment]
Let me quote myself from https://github.com/tldr-pages/tldr-node-client/pull/264#issuecomment-618780772
> If you advertise something without testing then it is not a matter if it will go sideways but when!
> I see two possibilities here:
> 
> 1. Either we keep stuff as is but test those older versions (LTS only!)
> 2. We go and follow others by stating v8+ only

`package.json` unfortunately wrongly advertises minimum supported NodeJS version:
https://github.com/tldr-pages/tldr-node-client/blob/b206ac7de17f130dd9d874b5304b47f0165b39d3/package.json#L24-L26
while in reality, I **believe** it works only with NodeJS `>=8`, and it is actually **tested** using the following version matrix:
https://github.com/tldr-pages/tldr-node-client/blob/b206ac7de17f130dd9d874b5304b47f0165b39d3/.github/workflows/test.yml#L16

Your version is:
> * NodeJS version
>   v6.17.1

so it simply fails due to unimplemented JavaScript constructs inside the provided engine.

Your best bet is to try with at least NodeJS `>=10`, it should work there.

**Comment by d0ye** [comment]
> Let me quote myself from [#264 (comment)](https://github.com/tldr-pages/tldr-node-client/pull/264#issuecomment-618780772)
> 
> > If you advertise something without testing then it is not a matter if it will go sideways but when!
> > I see two possibilities here:
> > 
> > 1. Either we keep stuff as is but test those older versions (LTS only!)
> > 2. We go and follow others by stating v8+ only
> 
> `package.json` unfortunately wrongly advertises minimum supported NodeJS version:
> https://github.com/tldr-pages/tldr-node-client/blob/b206ac7de17f130dd9d874b5304b47f0165b39d3/package.json#L24-L26
> 
> 
> while in reality, I **believe** it works only with NodeJS `>=8`, and it is actually **tested** using the following version matrix:
> https://github.com/tldr-pages/tldr-node-client/blob/b206ac7de17f130dd9d874b5304b47f0165b39d3/.github/workflows/test.yml#L16
> 
> Your version is:
> 
> > * NodeJS version
> >   v6.17.1
> 
> so it simply fails due to unimplemented JavaScript constructs inside the provided engine.
> 
> Your best bet is to try with at least NodeJS `>=10`, it should work there.

Thx! For convenience, I install node with yum, Seems it did not maintain an up to date version, After uninstalling tldr with npm, And update node with `npm install -g n` and `n stable` , it worked

**Comment by vladimyr** [comment]
Glad it worked! 🚀
If you don't mind I'm closing this issue but feel free to open PR to update the package.json engines field if you

**Comment by d0ye** [comment]
> Glad it worked! 🚀
> If you don't mind I'm closing this issue but feel free to open PR to update the package.json engines field if you like.

I'd love to help to improve，So others may avoid my issue . But I don't have any js or node background, so I can't figure the effects it may cause, May In the future I have enough background to estimate all effects so make a PR

BTW, Thx for the timely response 😄
