### ISSUE TITLE
`-o` and `--os` is not compliant with the client spec

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr-node-client#336]
According to the [client spec](https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md#arguments), the arguments for platform-specific commands should be `-p` and `--platform`. However, here it is `-o` and `--os`.

Reference: https://github.com/tldr-pages/tldr/pull/5508#issuecomment-808466616

**Comment by vladimyr** [comment]
Well as it is the case with any good spec implementation here simply precedes it 😀
