### ISSUE TITLE
When I go to exec the tldr --update command, `ECONNREFUSED` error is prompted

### ISSUE THREAD

**Issue by sanshiliuxiao** [tldr-pages/tldr-node-client#361]
## Expected behavior

It can be updated normallyIt can be updated normally

## Actual behavior

![1](https://user-images.githubusercontent.com/25658690/128584555-166d742b-31ae-4658-976d-1dd34498705b.png)

## Environment
- Operating system - Linux
- Node.js version  - 12.22.2
- tldr-node-client version - 3.3.7

**Comment by marchersimon** [comment]
`443` isn't the error code, it's just the port number (TCP). The error code is `ECONNREFUSED`.

**Comment by agnivade** [comment]
This sounds like a network connectivity issue. I don't think it's a bug in the code. Closing, but let me know if anyone wants to reopen.
