### ISSUE TITLE
tldr fails silently when trying to read invalid `.tldrrc` leading to confusion

### ISSUE THREAD

**Issue by T3sT3ro** [tldr-pages/tldr-node-client#365]
I come from here: https://github.com/tldr-pages/tldr/issues/1262

https://github.com/tldr-pages/tldr-node-client/blob/1641dea94df3aabcd36f381dcac61a50905a36ea/lib/config.js#L16-L21

There should be some error printed on error stream that the JSON object couldn't be loaded due to invalid syntax. JSON parse fails silently when the file is missing (that's OK), but SHOULD error when the config is invalid. Common examples when `*rc` files print errors include `.vimrc`, `.tmux.conf` and probably others.

The simplest case - yeet the ESlint directives and add proper error handling.

**Comment by marchersimon** [comment]
Whoops, wanted to request a review and forgot this is not a PR 😅
