### ISSUE TITLE
> It is a reasonable request. But since the pages are internal to your team, I am wondering how much effort is it to just periodically fetch the master pages and add your local set of pages. If there are multiple remote sources to merge from, that would be a valid request as keeping multiple sources in sync would be difficult.

### ISSUE THREAD

**Issue by Qdwrh** [tldr-pages/tldr-node-client#377]
> It is a reasonable request. But since the pages are internal to your team, I am wondering how much effort is it to just periodically fetch the master pages and add your local set of pages. If there are multiple remote sources to merge from, that would be a valid request as keeping multiple sources in sync would be difficult.

Private forks and uploading a zip to a non-public server makes it quite complex and uncomfortable.

> There is also another nuance to deal with multiple remotes - file name collision. Within a single source, the filesystem guarantees that all files have to be unique. But when the client needs to merge from multiple sources, the spec needs to clearly define what happens when there are pages with the same name from different sources.

You could just use the order of the "repositories" array: Newer entries will overwrite previous entries.

_Originally posted by @timonf in https://github.com/tldr-pages/tldr-node-client/issues/299#issuecomment-635236094_

**Comment by agnivade** [comment]
It's a repeat of the original comment. Let's track the repositories array feature request in the original issue. Closing.
