### ISSUE TITLE
Version 3.3.8 is not available in npm, latest there is 3.3.7

### ISSUE THREAD

**Issue by papb** [tldr-pages/tldr-node-client#387]
The latest tag here on GitHub is 3.3.8, but the [latest available on npm is 3.3.7](https://www.npmjs.com/package/tldr?activeTab=versions). Did you forget to publish?

**Comment by papb** [comment]
If anyone is also trying to use 3.3.8: you can tell npm to install directly from github as follows:

```
npm install -g https://github.com/tldr-pages/tldr-node-client/tarball/v3.3.8
```

**Comment by agnivade** [comment]
Yeah @owenvoke tagged a new release. But I have the npm permissions. @owenvoke - I can publish to npm if that's fine with you. Unless there's some other conversation which I missed.

**Comment by owenvoke** [comment]
@agnivade, that'd be great. I do also have permissions, although I think I thought we auto-released to npm.

**Comment by agnivade** [comment]
Oh I see, then please feel free to go ahead. Thanks!

**Comment by owenvoke** [comment]
@agnivade, my bad... I don't have permissions 😬 Was thinking this was the linter.

**Comment by agnivade** [comment]
Done. Sorry about the delay!

**Comment by papb** [comment]
Cool, thank you!
