### ISSUE TITLE
Transition from master to main branch

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr-node-client#400]
Are there any plans to transition from the `master` to the `main` branch for the node client? Or is it necessary for `npm`?

This would make this repo align with other repos in the org.

**Comment by owenvoke** [comment]
I don't think it's necessary for npm, as releases are published and don't rely on the branch. 👍🏻 This would be a good change to make for consistency.

**Comment by kbdharun** [comment]
Done with this change, will add CI to automatically sync the main branch with the master as repackaged clients might be building their packages from the master branch.
