### ISSUE TITLE
Feature request: update only specific languages in cache

### ISSUE THREAD

**Issue by Korkman** [tldr-pages/tldr-node-client#406]
## Feature request
Allow for a config option to download only specified languages. Bonus points for reading /etc/locale.gen (if applicable) and selecting languages to be downloaded accordingly (this would require some mapping effort).

Edit: or download the current language by default, like the python client, and allow specifying another language as argument.

**Comment by kbdharun** [comment]
Superseded by https://github.com/tldr-pages/tldr-node-client/issues/419
