### ISSUE TITLE
Fetch individual translation archives for cache based on the environment variable configuration

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr-node-client#419]
As specified in [Client Specification 2.0](https://github.com/tldr-pages/tldr/blob/v2.0/CLIENT-SPECIFICATION.md)

"If appropriate, it is RECOMMENDED that clients implement a cache of pages. If implemented, clients MUST download the entire archive either as a whole from https://tldr.sh/assets/tldr.zip (Which redirects to https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/main/assets/tldr.zip) or download language-specific translation archives in the format [https://tldr.sh/assets/tldr-pages.{{language-code}}.zip](https://tldr.sh/assets/tldr-pages.%7B%7Blanguage-code%7D%7D.zip) (Which redirects to [https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/main/assets/tldr-pages.{{language-code}}.zip](https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/main/assets)), along with the archive for English from https://tldr.sh/assets/tldr-pages.zip (It redirects to https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/main/assets/tldr-pages.zip).

Caching SHOULD be done according to the user's language configuration (if any), to not waste unneeded space for unused languages. Additionally, clients MAY automatically update the cache regularly."

So, we need to update the client behaviour to work with fetching only the specified language's archive when fetching based on configuration, we can include English by default as a fallback.

**Comment by vivekjoshi556** [comment]
I would like to work on this. Can you please assign it to me?

**Comment by kbdharun** [comment]
> I would like to work on this. Can you please assign it to me?

Sure
