### ISSUE TITLE
"tldr" on it's own should show more detailed usage

### ISSUE THREAD

**Issue by qw3rtman** [tldr-pages/tldr-node-client#42]
Currently, when I execute `tldr` on its own, I get:

```
28 Dec 11:03:49 - Usage: tldr <command>
```

Instead, I think showing the output of `tldr --help` would provide more useful information to the user. I don't think the date and time are very important; is there some other significance behind showing the date and time?

**Comment by igorshubovych** [comment]
Upgrade to 1.4.0
