### ISSUE TITLE
Option to output everything

### ISSUE THREAD

**Issue by amitzur** [tldr-pages/tldr-node-client#44]
First, this is rad :)
Since every command is byte size, I wanted an option to output everything and read it out to find out about commands I didn't know.
I tried to add an '--all' option, but then realized that cache.list returns also unavailable commands (e.g. apt-get on osx).
I think cache.list should return only platform-relevant commands. Then iterating over cache.list with tldr.get is a trivial implementation of this feature.
If you think this is a good idea I'll submit a pull request

**Comment by igorshubovych** [comment]
Good idea. Thank you.

**Comment by amitzur** [comment]
Should `trdr --list` return only the platform-relevant commands? Then it's another issue

**Comment by igorshubovych** [comment]
Closing this as the PR is closed.
