### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by VarunAgw** [tldr-pages/tldr-node-client#49]
I've recently installed this, but I am feeling it is bit slow

I did `time tldr ls`

It says:
```
real    0m0.477s
user    0m0.405s
sys     0m0.082s
```

It will be better if it can work faster. 500ms is bit too high.

**Comment by igorshubovych** [comment]
Which version of NodeJS do you have?
How fast do you think it should work?

**Comment by VarunAgw** [comment]
I checked it under v0.10.x and v4.x (both Ubuntu). I don't know exactly, but I feel 50ms will be good enough

**Comment by igorshubovych** [comment]
It runs for 310-390 ms on my machine in MacBook Air / OSX.
Empty test.js runs for 80ms.
Gulp with no Gulpfile (so it does nothing) runs for 290-360ms.

So I would say it is hard to make it significantly faster. I may try to exclude some modules, but I doubt I can decrease even to 200 ms.

If the speed is critical for you I would recommend using either C++ or Go client:
https://github.com/tldr-pages/tldr#clients

NodeJS client goals were different:
- reference client implementation
- speed of development

**Comment by rprieto** [comment]
Agreed with @igorshubovych. It would take a lot of profiling to bring it to ~200ms, not sure it's the top priority unfortunately.

But it does raise another question, having a lot of clients is nice for encouraging open-source and having lots of ideas, however it's very odd to have to
- direct people to certain clients if they want certain features, at the detriment of other features
- have to always ask which client people are using

Let's have a chat on Gitter about ways we can make this work better.

**Comment by VarunAgw** [comment]
Hi, I've created a simple script, which solved this problem in somewhat ways (by acting as caching).

	function tldr () {
		mkdir -p /tmp/tldr_cache
		
		if [ "--flush-cache" == $1 ]; then
			rm /tmp/tldr_cache/*
			return
		fi
		
		if [ "--" == "${1:0:2}" ]; then
			command tldr $*
			if [ "--help" = $1 ]; then
				echo -e "To flush the custom caching\n"
				echo -e "    $ tldr --flush-cache"
			fi
			return
		fi
		
		if [ -f "/tmp/tldr_cache/$1" ]; then
			cat /tmp/tldr_cache/$1
		else
			script -q -c "tldr $1" /tmp/tldr_cache/$1
			sed '1d' /tmp/tldr_cache/$1 > /tmp/tldr_cache/$1.tmp;
			mv /tmp/tldr_cache/$1.tmp /tmp/tldr_cache/$1
		fi
	}

**Comment by VarunAgw** [comment]
@rprieto I personally don't like the concept of multiple clients. I tried some tldr-pages client today. Each one of them was lacking something, or was slow. So instead of 10, I'll prefer a single good client.

Like this client has color coding and now with caching I am good to go!

**Comment by waldyrious** [comment]
That's an interesting point: we could provide basic specs expected from clients, such as the ability to color tokens, perform search, caching, work on dark or light backgrounds, and so on. That way we get the benefit of clients specialized on e.g. speed, or working on specific platforms or environments, without losing on the functionality side.

**Comment by ostera** [comment]
@VarunAgw you seem to be a smart fella, why don't you have a crack at the node-client and try to make it a bit faster? 

@waldyrious :+1:

**Comment by amitzur** [comment]
I did a bit of profiling and it seems like the bulk of time is coming from require("request")
it takes ~250ms on my MacBook Pro

**Comment by rprieto** [comment]
Thanks for that @amitzur! Might be worth checking if we can use raw `require('http')` instead.

Just to confirm, if you comment out `require('request')` do we incur the loading time somewhere else, or does it really save 250ms? (should not crash if you have a local cache)

**Comment by amitzur** [comment]
It does take off ~50% on my machine. from 500ms to 250ms on average. There are other things I didn't find that comprise the rest 250ms

**Comment by amitzur** [comment]
require("unzip2") is also a few dozen ms

**Comment by igorshubovych** [comment]
Maybe we can use node-fetch instead of request.

**Comment by igorshubovych** [comment]
Please update to 1.4.0.
Thanks for idea and investigation!

**Comment by VarunAgw** [comment]
Thanks! That a huge improvement
