### ISSUE TITLE
tldr --list should return only platform-relevant commands

### ISSUE THREAD

**Issue by amitzur** [tldr-pages/tldr-node-client#50]
Either that or provide an indication for commands that are platform-specific.
I tried to run svcs on my OSX until I realized it's in the sunos folder :)

**Comment by igorshubovych** [comment]
@amitzur do you still consider this a problem?

**Comment by amitzur** [comment]
Yes as discussed in pull request #45

**Comment by igorshubovych** [comment]
In your opinion, what should be the command to print all the commands?

**Comment by amitzur** [comment]
I think you were right suggesting --list-all

**Comment by igorshubovych** [comment]
Upgrade to 1.5.1
