### ISSUE TITLE
Commands with spaces in them

### ISSUE THREAD

**Issue by denis-sokolov** [tldr-pages/tldr-node-client#57]
It would be great if `tldr git log` returned me the page for `tldr git-log`.
A minor quality-of-life improvement.

I even have a crappy Bash wrapper to solve this for me: `function t(){ local s=$([ -z "$2" ] && echo '' || echo "-$2"); echo tldr "$1$s"; }`

**Comment by waldyrious** [comment]
:+1:

**Comment by rprieto** [comment]
This seems to be covered by #47. Let me know if you meant something else.

**Comment by denis-sokolov** [comment]
Right! Sorry about the duplicate!

**Comment by waldyrious** [comment]
:confounded: sorry, I really ought to have remembered there was already an open issue for this.
