### ISSUE TITLE
Multi-line examples not rendering

### ISSUE THREAD

**Issue by rubenvereecken** [tldr-pages/tldr-node-client#64]
Take a look at [ls](https://github.com/tldr-pages/tldr/blob/master/pages/common/ls.md). Now try `tldr ls`. Two examples are missing: the ones with multiple lines. Coincidence? I think not.

**Comment by igorshubovych** [comment]
See #27

**Comment by rubenvereecken** [comment]
I missed out on that one. I took pains to enable multiple examples in the linter. I could easily generate an error for it. The problem is that using this feedback won't enable me to quickly "fix" these pages as I would with wrong syntaxes. I'll generate a list in a tldr issue and we can work from there.

**Comment by igorshubovych** [comment]
cc @rprieto

**Comment by agnivade** [comment]
There are no more multi-line examples in the repo anymore. All of them are taken care of by the PRs mentioned above. Until, the need arises to support multi-line examples, closing this.

P.S. - This was a nifty command to search for multi-line patterns- 
```
grep -R -Pzo '^`.*\n`.*' *`
```
