### ISSUE TITLE
Bold text is deleted

### ISSUE THREAD

**Issue by oxguy3** [tldr-pages/tldr-node-client#77]
This client handles bold text incorrectly. In Markdown, when some text is surrounded with asterisks, it should be made bold. This client, however, completely removes the text instead of emboldening it. The tldr page [csvcut](https://github.com/tldr-pages/tldr/blob/master/pages/common/csvcut.md) is an example of this; in the third example, the word "except" is completely removed.

![screen shot 2016-02-05 at 11 55 15 am](https://cloud.githubusercontent.com/assets/796881/12852980/a3e8e27e-cbff-11e5-864e-a4012995c870.png)

**Comment by rubenvereecken** [comment]
Nice catch, might have a look at this myself.
