### ISSUE TITLE
No color in Cygwin?

### ISSUE THREAD

**Issue by RShadowhand** [tldr-pages/tldr-node-client#87]
[In cygwin](http://i.imgur.com/F1W7jyU.png).
[In Cent7](http://i.imgur.com/ern2X7O.png).

I use Mintty with zsh. Mintty is set to xterm-256color. Identical .zshrc.
Editing .tldrrc doesn't work as I believe it's never loaded. I tried putting it in ~/ and in C:\Users\user.
I'm using the latest version.

**Comment by RShadowhand** [comment]
Adding "process.stdout.isTTY = true;" to the top of tldr.js fixed the problem. Marking as solved. Thanks for reading.

**Comment by igorshubovych** [comment]
Can you plz submit an PR with FAQ section in README.md about this?

**Comment by RShadowhand** [comment]
Of course. Give me a sec :)

**Comment by RShadowhand** [comment]
`npm remove -g tldr`
`npm install -g tldr-cyg`

https://github.com/RShadowhand/tldr-node-client-cygwin

**Comment by igorshubovych** [comment]
Why forking? It can be done with config option.

**Comment by RShadowhand** [comment]
I'll add proper cygwin support in the coming days, and then make a pull request. I'm too busy trying to meet a deadline for tomorrow. Expect more by monday.

**Comment by igorshubovych** [comment]
ok. got it.

**Comment by RShadowhand** [comment]
Upon further inspection, I found that the problem lies within [colors.js](https://github.com/Marak/colors.js), and not tldr-node-client itself.

My fork is useless, and I'll remove it, and see if I can fix colors.js instead. Meanwhile I'll make a pull request to this with a README.md changes to include info on how to battle this in various ways until my fork is accepted to colors.js.
