### ISSUE TITLE
tldr has trouble displaying *file* part on console

### ISSUE THREAD

**Issue by chuanconggao** [tldr-pages/tldr-node-client#94]
## Expected behaviour
`tldr tac` should show:

----
tac

Print and concatenate files in reverse.

- Print the contents of _file1_ reversed to the standard output:

  `tac {{file1}}`

----

This is the correct behavior of web client.

## Actual behaviour
However, on console it actually shows

----
tac

Print and concatenate files in reverse.

- Print the contents of&nbsp;&nbsp;reversed to the standard output:

  `tac {{file1}}`

----

Here the _file1_ part (`*file1*` in Markdown) of the description is missing.
## Environment
- Operating system - OSX
- NodeJS version - v5.9.0

**Comment by agnivade** [comment]
Thanks for reporting. Its the same as #77. Fix coming soon !
